### ISSUE TITLE
Clicking on a tank to apply Blistering scales not working

### ISSUE THREAD

**Issue by youdontknowmu** [Xenknight61/EvokerAug#10]
Hello there, and thanks for this marvellous addon !!

There seems to be a problem with blistering scales when in a mixed group with alliance/horde players

Whenever I left-click on a tank that is not my faction (declared as a tank in the group and correctly seen as one by your addon since it's sorted with tanks), nothing happens.
If I target him manually, and cast blistering, it works.

I will do some more testing with no mixed factions, but this case does not work ATM

Thanks again !

**Comment by Xenknight61** [comment]
I can't test it right now, I will do my tests when raid and m+ are opened and make adjustments accordingly, thank you.

**Comment by youdontknowmu** [comment]
Ok,

I did a little more testing tonight, with a guy from the same faction.
I still don't work for tanks, but still is OK for DPS

Using the AutoFill feature, I managed to cast the scales on the tank (not targeted), while hovering the EvokerAug frame, but using the shortcut for blistering scales from my skill bar.
So it seems to work but not with the "left click" feature on tanks

Hope it helps

**Comment by Xenknight61** [comment]
Have you ever tested whether it works if you assign it to another key?

**Comment by Xenknight61** [comment]
3dbed9c6c528cfd023e5f3d89d2d481d83d60dbb 

problem solved

**Comment by youdontknowmu** [comment]
Ok nice, is it a new version coming ?
I used it again yesterday but still no blistering scale on tanks when clicking, even if I change my keybind :)

**Comment by Xenknight61** [comment]
> Ok nice, is it a new version coming ? I used it again yesterday but still no blistering scale on tanks when clicking, even if I change my keybind :)

yes, you can use it with v1.0.17
