### ISSUE TITLE
Bar colors not OK on DPS (but OK on tanks)

### ISSUE THREAD

**Issue by youdontknowmu** [Xenknight61/EvokerAug#11]
Hello there,

After some more tesing on NM and HM I have a few more things to add :

- Bars does not fade nor becomes gray after one DPS dies, making it difficult to see if he's still prescienceable
- Bar colors (class colors) does not work for added DPS, but works for Tanks (All DPS are light grey, but tanks correctly have their classe colors)

I hope you find where it comes from, this addon is great :)

Have a nice day

**Comment by Xenknight61** [comment]
![image](https://github.com/user-attachments/assets/cb488aef-fe00-4435-a846-3f36742b0229)
bar colors are colored according to class

**Comment by youdontknowmu** [comment]
I'll do a bit more testing tonight, might be a problem with elvui ?

I'll make you a screenshot, only tanks a correctly colored but dps are all grey

**Comment by Xenknight61** [comment]
128802299b09318ab486aa1a11470dc3eae9c6e3

with v1.0.18
when the player dies, it will be grey and pale, and DEAD will be written next to the name of the deceased

thank you for your suggestions

**Comment by Xenknight61** [comment]
> I'll do a bit more testing tonight, might be a problem with elvui ?
> 
> I'll make you a screenshot, only tanks a correctly colored but dps are all grey

Elvui can do it. Can you test it and let me know?

**Comment by youdontknowmu** [comment]
Yes I will try to troubleshoot this way

- start with only evokeraug addon and see
- reload the ui each time with one more addon of my UI until it bugs again

I'm also starting to wonder if it's not because I mainly play with people from another server and sometimes you have to hook their unit frame with 
''Name - server'' instead of just ''name''

Like 
EvokerPlayer - Hyjal
SomeRadomGuy - Arathi


I'll keep you in touch, I'll play a bit Saturday.

Still have to thank you because we are HM 7/8 and I'm rocking your addon !
