### ISSUE TITLE
[SUGGESTION] - Making Sense Power visible on DPS

### ISSUE THREAD

**Issue by youdontknowmu** [Xenknight61/EvokerAug#14]
Hi again !

One great thing with augmentation evoker is that they have Sense Power aura that adds on every party member an aura whenever they use a good offensive cooldown.

https://www.wowhead.com/spell=361021/sense-power

On Raidframes and while mouserovering a player, you can see witch party member is on a cooldown, thus making it easyier to target the correct people with Prescience.
Your addon could greatly benefit from showing the Sense Power Icon on DPS that have the aura.

Have a nice day !

**Comment by Xenknight61** [comment]
128802299b09318ab486aa1a11470dc3eae9c6e3

with v1.0.18
Sense Power has been added to the buff list for better visibility and if the player has it, it has been adjusted to be gowl in frame.

thank you for your suggestions
