### ISSUE TITLE
[SUGGESTION] - Bookmark DPS (Favorites)

### ISSUE THREAD

**Issue by youdontknowmu** [Xenknight61/EvokerAug#15]
Hello again,

Maybe the " add every DPS in the raid" is not a good idea you are right, at least not on "auto mode", maybe just a click button to add every DPS could do the trick.

But I think having a way to "right-click -> add DPS to favorite list" could be a major upgrade :

Like, if you play Aug in a guild or a regular player base, you'll start to know each other and discord, and always prescience the same guys
If you have a feature like bookmark, you can tell the addon to ALWAYS ADD the people in the favorite list when you group with them (and they are in DPS spec).

This way, no bothering with adding alway the same people, and if you play frequently with the same good DPS they will always show in your list without bothering to add them. Even after a crash, or a /reloadUI

What do you think of that ? :D

**Comment by Xenknight61** [comment]
nice idea i can do that
I'll think about it a little more, if I don't think of anything else I'll do it.

**Comment by Xenknight61** [comment]
a00d196cba301aa711677813039783228cf77419
I added a favorite option, the frame will be added automatically when the party enters

**Comment by youdontknowmu** [comment]
Splendid !! =)
